### PR TITLE
Fix compliance

### LINKED ISSUE #167: Compliance issues
The following compliance issues have been found for this repository. Please see the checklist below.
#### Compliance issue for IsValidConvertMethodName
 - [x] Convert method name invalid: Method name must begin with either 'ITo' or 'To' or 'IFrom' or 'From' and not contain 'ToBHoM' or 'FromBHoM' in Test_Toolkit\CodeComplianceTest_Engine\Convert\ToBHoM.cs at line 34, column 27

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #167 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

File: CodeComplianceTest_Engine/Convert/ToBHoM.cs [hunk 1]
```diff
@@ -31,7 +31,7 @@ namespace BH.Engine.Test.CodeCompliance
 {
     public static partial class Convert
     {
-        public static Span ToBHoM(this Microsoft.CodeAnalysis.Text.TextSpan span)
+        public static Span ToSpan(this Microsoft.CodeAnalysis.Text.TextSpan span)
```
Comment (awakeman) [inline CodeComplianceTest_Engine/Convert/ToBHoM.cs]: This needs moving into ToSpan.cs (it already exists) and this file can then be deleted.

Comment (FraserGreenroyd) [reply CodeComplianceTest_Engine/Convert/ToBHoM.cs]: Done
