### PR TITLE
Fix null exception bug in property accessors if they are null

### LINKED ISSUE #163: PropertyAccessorsHaveNoBody fails if AccessorList is null
As title.

They shouldn't ever be `null` - but if they are it throws a `NullReferenceException` so should be handled.

An additional test should be added to make sure AccessorList is not null if it's not already done elsewhere, will add another issue for that after investigation.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #163 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

File: CodeComplianceTest_Engine/Query/Checks/HasPublicGet.cs [hunk 1]
```diff
@@ -42,7 +42,10 @@ public static partial class Query
         public static Span HasPublicGet(PropertyDeclarationSyntax node)
         {
             AccessorDeclarationSyntax getter = node.PropertyGetAccessor();
-            return (getter == null || getter.IsPrivate()) ? getter.Modifiers.Span.ToBHoM() : null;
+            if (getter == null)
+                return node.Modifiers.Span.ToBHoM();
```
Comment (awakeman) [inline CodeComplianceTest_Engine/Query/Checks/HasPublicGet.cs]: Could we use maybe the span of the name or something rather than of the property modifiers?

Comment (FraserGreenroyd) [reply CodeComplianceTest_Engine/Query/Checks/HasPublicGet.cs]: According to intellisense `PropertyDeclarationSyntax` did not have a name property, but it did have its own span so I've changed to that if that's ok?
