### PR TITLE
Rule out test assemblies from versioning test sets

### LINKED ISSUE #486: Fix issue with Test_Toolkit methods and objects being part of versioning testset
#### Description:

Code added in https://github.com/BHoM/Test_Toolkit/pull/481 if used to generate versioning test sets means that objects and methods from versioning toolkit itself gets included in the generated files. This should be avoided.

#### Steps to reproduce:

Run methods in linked PR

#### Expected behaviour:

For no trace of methods from Test_Toolkit to be included in the versioning test methods, types and adapters

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #486

 

Explicitly rule out any type or method from a Test_Toolkit assembly from being included in test sets.

 ### Test files

Ensure no test_Toolkit method is part of the included methods/types

[GenerateLegacyDataset.zip](https://github.com/user-attachments/files/17109553/GenerateLegacyDataset.zip)

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@adecler after doing this I had another thought. Could potentially make use of the `IsPrototype` method in the BHoM_Engine instead as that should filter out everything not part of the beta (if the beta is the last installer you ran). Might be worth a quick chat before I make that change, but might be a cleaner solution.

File: Test_Engine/Query/IsTestToolkit.cs [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                return false;
+
+            return method.DeclaringType.IsTestToolkit();
+        }
+
+        /***************************************************/
+        /**** Private Fields                            ****/
+        /***************************************************/
+
+        private static HashSet<string> m_testToolkitAssemblyNames = new HashSet<string> { "CodeComplianceTest_Engine", "CodeComplianceTest_oM", "InteroperabilityTest_Engine", "InteroperabilityTest_oM", "NUnit_Engine", "NUnit_oM", "Test_Engine", "TestRunner", "UnitTest_Engine", "UnitTest_oM" };
```
Comment (pawelbaran) [inline Test_Engine/Query/IsTestToolkit.cs:69]: I would consider splitting the collection with line breaks for readability

**Review by pawelbaran — COMMENTED** [review]
Makes sense in general, just one thought for an alternative: filtering by assembly method that would take:
- a collection of types/methods
- a collection of strings correspondent to assembly names
- bool ignore vs include

...could be helpful in other places as well. But just a thought, please feel free to ignore 😉

**Review by pawelbaran — APPROVED** [review]
Changes make sense, happy to approve 👍 

image

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling
@BHoMBot check project-compliance
@BHoMBot check serialisation
